package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
All tests passed
kindly review @bondz
=> Obriens' solution to mini-challenge-3

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js, src/list-sorting/test.js
=> Solution to week 3's mini challenges

package-lock.json, src/binary-reversal/README.md, src/binary-reversal/index.js, src/list-sorting/index.js
=> Solution to mini-challenge-3

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
* A String Integer value was given as parameter to the function
i. I had to convert first to Number
ii. use `toString` method and passed 2 as the target base of conversion to derive the binary equivalent
iii. used the `padStart` method to add extra 0's to meet 8 bit, if the binary equivalent is not 8 bit
iv. reversed the bit using `while` loop
v. used `ParseInt` Method to get the decimal equivalent of the reversed bit
* An element and An array was passed as parameter to the function
> The Idea is to return the last position where the element is found in the Array
i. I had to check for empty array and return -1
ii. For multi-dimensional array; I used the `.constructor` method to check if the first element of an Array is also an Array, Then I had to dynamically keep the position where the …
=> Solution to Binary-Reversal and List Sorting

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
please review my solution and give me feedback
=> Challenge completed

src/binary-reversal/index.js, src/list-sorting/index.js
All the test passed.
I made some little change to my code implementation as advised in the  last algorithm such as:
- Avoided mutation. 
- Tried to take cognizance of formatting style. and
- Avoided too many loops.
Thanks
=> My solution to mini-challenges-3

src/binary-reversal/index.js, src/list-sorting/index.js
algorithms solved. Kindly review
=> Solutions to The Algorithms

src/binary-reversal/index.js, src/list-sorting/index.js
Completed binaryReversal and listSorting functions
=> Attempted Week 3 Challenge

src/binary-reversal/index.js, src/list-sorting/index.js
- The two index.js files of the algorithms for mini-challenges-3 have been worked on.
=> mini-challenges-3 index files updated

src/binary-reversal/index.js, src/list-sorting/index.js
All test passed.
Kindly review @bondz
_Thanks in anticipation_
=> Solutions to mini-challenges-3

.vscode/launch.json, package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
i seem to be well to do with when i input the numbers in my code from the test file and run it. but the npm test is bringing up a strange figure. please help.
=> Binary-reversal

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
mini-challenges-3 solved by Oladokun Oladapo
=> mini-challenges-3 solved

src/binary-reversal/index.js, src/list-sorting/index.js
Requesting PR review and merge.
=> Mini Challenge 3 Solved

src/binary-reversal/index.js, src/list-sorting/index.js
solved the algorithm
- binary reversal
- list sorting
=> solution to the algorithm

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
=> challenge 3

src/binary-reversal/index.js, src/list-sorting/index.js
Solutions passed all test cases.
Please provide any helpful tips.
Thank you.
=> Completed Solution to challanges

src/binary-reversal/index.js, src/list-sorting/index.js
Reverts decadevs/mini-challenges-3#24
=> Revert changes to master.

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
=> Different data structure used

package-lock.json, src/binary-reversal/index.js, src/list-sorting/index.js
I will love to get a feedback for the solution.
Thanks in advance
=> mini-challenge-3 solution

src/binary-reversal/index.js, src/list-sorting/index.js
Solve the algorithm
- binary reversal
- list sorting
=> algorithms solved
